---
title: "Linear Model"
author: "Jeanette Serrano"
date: "11/2/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dataF <- read.csv(file="http://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt",sep="",header=TRUE)
```


```{r include=FALSE}
require(tidyverse)
require(tigerstats)
require(rgl)
require(knitr)
```


Plot scatterplot

```{r}
plot(SIMS~ARM,data=dataF)
```


```{r}
basicNN <- ggplot(dataF,aes(y=SIMS,x=ARM))
```

Now add in scatterplot



```{r}
basicNN + geom_point()+ geom_smooth(method=lm)
```

```{r}
plot(SIMS~GRIP,data=dataF)
```

```{r}
basicNN <- ggplot(dataF,aes(y=SIMS,x=GRIP))
```
  
```{r}
basicNN + geom_point()+ geom_smooth(method=lm)
```  
    
Now add in scatterplot
  
Plot of SIMS~GRIP~ARM will look like a plane in 3 dimensional space. We don't know how or have the tools to plot it. 


```{r}
model.1 <- lm(SIMS~ARM,data=dataF)
summary.lm(model.1)
```
```{r}
model.2 <- lm(SIMS~GRIP,data=dataF)
summary.lm(model.2)
```

```{r}
model.3 <- lm(SIMS~GRIP+ARM,data=dataF)
summary.lm(model.3)
```
  
The adjusted R-squared for Model 1 for ARM is better then GRIP. Model 2 is the worst and Model 1 is the second best and the best Model is Model 3.   
  